FROM mysql:8.4

RUN mkdir -p /var/lib/mysql-keyring && \
    chown -R mysql:mysql /var/lib/mysql-keyring && \
    chmod 750 /var/lib/mysql-keyring

COPY mysql_keyring.cnf /etc/mysql/conf.d/keyring.cnf
RUN chmod 644 /etc/mysql/conf.d/keyring.cnf && \
    chown mysql:mysql /etc/mysql/conf.d/keyring.cnf
